# Generated by Django 4.0 on 2022-02-22 03:16

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_choice_poll_vote_choice_poll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
